[tool.black]
line-length = 120
include = '\.pyi?$'
force-exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
| tests.py
| manage.py
'''