TEXT_FIELD = 2000
CHAR_FIELD = 30
EMAIL_FIELD = 60

SIGN_UP_TEMPLATE = 'sign_up.html'
LOGIN_TEMPLATE = 'login.html'

MAIN_PAGE = '/'
SIGN_UP = '/signup/'
LOGIN = '/login'
LOGOUT = '/logout/'

USERNAME_HELP_TEXT = 'Please, enter your email or phone number here.'

NAME_CHARFIELD_LENGTH = 100
CODE_CHARFIELD_LENGTH = 40
HUGE_CHARFIELD_LENGTH = 500
PRICE_DECIMALFIELD_DIGITS_LENGTH = 9
PRICE_DECIMALFIELD_DECIMAL_LENGTH = 2

